# -*- coding: utf-8 -*-
"""fiston .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoM8-Gn4fo_XQfW4zYHRVD4GKlyrQXve
"""



import pandas as pd

# Define phishing keywords
phishing_keywords = ["urgent", "password reset", "bank", "verify", "account suspended"]

# Load the dataset (uploaded file)
emails_df = pd.read_csv("/content/2405000313.csv")

# Check if the 'content' column exists
if 'content' in emails_df.columns:
    # Apply phishing detection
    emails_df["is_phishing"] = emails_df["content"].apply(
        lambda x: any(keyword in str(x).lower() for keyword in phishing_keywords)
    )

    # Save the processed file
    emails_df.to_csv("/content/analyzed_2405000313.csv", index=False)

    # Print completion message
    print("Phishing detection complete. ✅")
else:
    print("Error: The 'content' column is missing from the dataset.")