# -*- coding: utf-8 -*-
"""SANO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDb9PcxLNPO5HW3FqFIFjpAc2H2C7AER
"""



import random
def jaccard_similarity(file1, file2):
    # Split texts into set of words
    set1 = set(file1.split())
    set2 = set(file2.split())

#the jaccard_similarity of function now return both the similarity score and the set of common words
# the intersecton variable contains the words that that appear in both file1 and file2.
# the common_words set is printed alongside the similarity score.

    # Find intersection and union
    intersection = set1.intersection(set2)
    union = set1.union(set2)

    # Calculate Jaccard similarity
    similarity = len(intersection) / len(union)

    # Return similarity and intersecting words
    return similarity, intersection

# Input texts
file1 = "History is the systematic study of the past."
file2 = "History is the systematic study of the past this is just for practice."

# Calculate the similarity and get common words
similarity, common_words = jaccard_similarity(file1, file2)

# Print results
print(f"Similarity Score: {similarity:.2f}")
print(f"Common Words: {common_words}")